name: Demo to create automatic PR

on:
  push:
    branches:
      - image-update

jobs:
  updateAuthor:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract git commit data
        uses: rlespinasse/git-commit-info-action@v1.x

      #- name: Update author information
        #run: echo "${{ env.GIT_COMMIT_AUTHOR_NAME }}" > AUTHOR

      - name: Create PR
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GH_TOKEN }}
          branch: auto-pr-branch
          committer: "${{ env.GIT_COMMIT_AUTHOR_NAME }} <${{ env.GIT_COMMIT_AUTHOR_EMAIL }}>"
          author: "${{ env.GIT_COMMIT_AUTHOR_NAME }} <${{ env.GIT_COMMIT_AUTHOR_EMAIL }}>"
          title: "demo for auto pr"
          body: "This is a demo for auto pull request"
          commit-message: "chore: update AUTHOR file with latest committer info"
          delete-branch: true
