name: Reusable PR Creator

on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string
      base:
        required: true
        type: string
      pr_title:
        required: true
        type: string

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Automated PR from reusable workflow"
          title: ${{ inputs.pr_title }}
          base: ${{ inputs.base }}
          branch: ${{ inputs.branch }}
